import type { Product } from "../drizzle/schema";
import { invokeLLM } from "./_core/llm";

type SalesAssistantInput = { budget?: string; useCase: string; games?: string; programs?: string; preferences?: string };
type Recommendation = { product: Product; score: number; reason: string };
export type SalesAssistantResult = { recommendation: { id: number; reason: string; message: string; arguments: string[]; objections: string[] } | null; alternatives: Array<{ id: number; reason: string }>; usedFallback: boolean };

function normalize(value: unknown) { return String(value ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); }
function parseBudget(value?: string) { if (!value) return undefined; const digits = value.replace(/[^0-9,.-]/g, "").replace(/\.(?=\d{3}(?:\D|$))/g, "").replace(",", "."); const parsed = Number(digits); return Number.isFinite(parsed) && parsed > 0 ? parsed : undefined; }
function parsePrice(product: Product) { return parseBudget(product.promoPrice || product.price); }
function productText(product: Product) { return normalize([product.brand, product.model, product.processor, product.generation, product.ram, product.storage, product.gpu, product.category, product.notes].join(" ")); }
function inferKeywords(input: SalesAssistantInput) { return normalize([input.useCase, input.games, input.programs, input.preferences].filter(Boolean).join(" ")).split(/\s+/).filter((word) => word.length >= 4); }
function scoreProduct(product: Product, input: SalesAssistantInput): Recommendation {
  const text = productText(product); const keywords = inferKeywords(input); const budget = parseBudget(input.budget); const price = parsePrice(product); let score = 0; const reasons: string[] = [];
  for (const keyword of keywords) if (text.includes(keyword)) score += 8;
  const use = normalize(input.useCase);
  if (/(jogo|game|gamer|jogar)/.test(use)) { if (!/integrada|uhd|vega 3|vega 5/.test(normalize(product.gpu))) { score += 12; reasons.push("placa de vídeo dedicada ou mais preparada para jogos"); } }
  if (/(trabalho|estudo|office|navegar|faculdade)/.test(use)) { if (product.category === "Notebook") score += 8; reasons.push("formato prático para a rotina"); }
  if (/(edicao|edição|video|vídeo|design|render)/.test(use)) { if (/16\s*gb|32\s*gb/.test(productText(product))) score += 10; if (!/integrada|uhd/.test(normalize(product.gpu))) score += 6; reasons.push("configuração mais confortável para tarefas pesadas"); }
  if (budget && price) { if (price <= budget) { score += 20; reasons.push("fica dentro do orçamento informado"); score += Math.max(0, 8 - Math.round(((budget - price) / budget) * 8)); } else score -= Math.min(24, Math.round(((price - budget) / budget) * 24)); }
  if (product.promoPrice) { score += 3; reasons.push("está em oferta"); }
  return { product, score, reason: reasons.slice(0, 3).join(", ") || "é uma opção disponível no catálogo e compatível com o perfil informado" };
}
export function rankProducts(products: Product[], input: SalesAssistantInput) { return products.filter((product) => product.status === "available").map((product) => scoreProduct(product, input)).sort((a, b) => b.score - a.score || a.product.id - b.product.id).slice(0, 5); }
function fallbackResult(ranked: Recommendation[], input: SalesAssistantInput): SalesAssistantResult { const best = ranked[0]; if (!best) return { recommendation: null, alternatives: [], usedFallback: true }; const displayName = `${best.product.brand} ${best.product.model}`; const price = best.product.promoPrice || best.product.price; return { recommendation: { id: best.product.id, reason: `Eu começaria pelo ${displayName}: ${best.reason}. Valor atual: ${price}.`, message: `Pelo que você me contou, eu começaria pelo ${displayName}. Ele combina com ${input.useCase || "a sua rotina"} e está por ${price}. Se quiser, te passo fotos e confirmo os detalhes da configuração.`, arguments: [best.reason, `Configuração: ${best.product.processor}, ${best.product.ram}, ${best.product.storage} e ${best.product.gpu}.`, "Equipamento disponível no catálogo C7 Store e revisado pela equipe."], objections: ["Se o orçamento estiver mais apertado, posso apresentar uma alternativa mais econômica.", "Se você precisar de mais desempenho, vale comparar com a próxima opção antes de decidir."] }, alternatives: ranked.slice(1, 3).map(({ product, reason }) => ({ id: product.id, reason })), usedFallback: true }; }
function textFromResponse(content: unknown) { if (typeof content === "string") return content; if (!Array.isArray(content)) return ""; return content.filter((part): part is { type: "text"; text: string } => Boolean(part && typeof part === "object" && (part as { type?: unknown }).type === "text" && typeof (part as { text?: unknown }).text === "string")).map((part) => part.text).join("\n"); }
export async function buildSalesAssistantResult(products: Product[], input: SalesAssistantInput): Promise<SalesAssistantResult> {
  const ranked = rankProducts(products, input); const fallback = fallbackResult(ranked, input); if (!ranked.length) return fallback;
  try {
    const catalog = ranked.map(({ product, reason }) => ({ id: product.id, name: `${product.brand} ${product.model}`, category: product.category, processor: product.processor, ram: product.ram, storage: product.storage, gpu: product.gpu, price: product.promoPrice || product.price, reason }));
    const response = await invokeLLM({ model: "gpt-5-mini", maxTokens: 900, messages: [{ role: "system", content: "Você é uma colega experiente de vendas da C7 Store. Escreva em português brasileiro, com calor humano, clareza e objetividade. Você trabalha nos bastidores para orientar a vendedora: nunca diga que é IA, robô ou sistema. Use somente os produtos e dados do catálogo recebido. Não invente especificações, preços, disponibilidade ou garantias. Escolha apenas IDs presentes no catálogo. A mensagem de WhatsApp deve soar como uma sugestão que a vendedora pode revisar, nunca como envio automático." }, { role: "user", content: JSON.stringify({ perfil: input, catalog }) }], responseFormat: { type: "json_schema", json_schema: { name: "sales_assistant_response", strict: true, schema: { type: "object", properties: { recommendationId: { type: "integer" }, reason: { type: "string" }, message: { type: "string" }, arguments: { type: "array", items: { type: "string" } }, objections: { type: "array", items: { type: "string" } }, alternativeIds: { type: "array", items: { type: "integer" } } }, required: ["recommendationId", "reason", "message", "arguments", "objections", "alternativeIds"], additionalProperties: false } } } });
    const parsed = JSON.parse(textFromResponse(response.choices[0]?.message.content ?? "{}")) as { recommendationId?: number; reason?: string; message?: string; arguments?: string[]; objections?: string[]; alternativeIds?: number[] }; const allowed = new Map(ranked.map(({ product }) => [product.id, product])); const chosen = parsed.recommendationId ? allowed.get(parsed.recommendationId) : undefined; if (!chosen || !parsed.reason || !parsed.message) return fallback;
    return { recommendation: { id: chosen.id, reason: parsed.reason, message: parsed.message, arguments: parsed.arguments ?? [], objections: parsed.objections ?? [] }, alternatives: (parsed.alternativeIds ?? []).filter((id) => id !== chosen.id && allowed.has(id)).slice(0, 3).map((id) => ({ id, reason: ranked.find(({ product }) => product.id === id)?.reason ?? "Alternativa disponível no catálogo." })), usedFallback: false };
  } catch (error) { console.warn("[SalesAssistant] Using deterministic fallback:", error instanceof Error ? error.message : error); return fallback; }
}
