import { useEffect, useMemo, useRef, useState } from "react";
import { Check, Download, ImageDown, Instagram, Loader2, Share2, X } from "lucide-react";

export type CardProduct = { id: number; brand: string; model: string; category: string; processor: string; ram: string; storage: string; screen: string; condition: string; cosmeticCondition?: string | null; price: string; promoPrice?: string | null; imageUrl?: string | null };
type Format = "whatsapp" | "square" | "story";
type Theme = "classic" | "light" | "offer";
type Options = { format: Format; theme: Theme; headline: string; showProcessor: boolean; showSpecs: boolean; showCondition: boolean; showPrice: boolean; showContact: boolean; imageFit: "contain" | "cover" };
const FORMATS = { whatsapp: { width: 1080, height: 1350, label: "WhatsApp 4:5" }, square: { width: 1080, height: 1080, label: "Instagram 1:1" }, story: { width: 1080, height: 1920, label: "Stories 9:16" } } as const;
const THEMES = { classic: { top: "#061b31", bottom: "#087fb2", accent: "#26baff", paper: "#ffffff", text: "#08233b", soft: "#567083" }, light: { top: "#dff5ff", bottom: "#80d9ff", accent: "#0879ad", paper: "#ffffff", text: "#08233b", soft: "#567083" }, offer: { top: "#3b0b20", bottom: "#d63b67", accent: "#ffcc58", paper: "#fff9f2", text: "#30101c", soft: "#775460" } } as const;

function loadUrl(url: string) { return new Promise<HTMLImageElement>((resolve, reject) => { const image = new Image(); image.crossOrigin = "anonymous"; image.onload = () => resolve(image); image.onerror = reject; image.src = url; }); }
function roundedRect(ctx: CanvasRenderingContext2D, x: number, y: number, width: number, height: number, radius: number) { ctx.beginPath(); ctx.roundRect(x, y, width, height, radius); ctx.closePath(); }
function fitText(ctx: CanvasRenderingContext2D, text: string, maxWidth: number, initial: number, min = 28) { let size = initial; while (size > min) { ctx.font = `800 ${size}px Arial`; if (ctx.measureText(text).width <= maxWidth) break; size -= 2; } return size; }

async function renderCard(canvas: HTMLCanvasElement, product: CardProduct, options: Options) {
  const { width, height } = FORMATS[options.format]; canvas.width = width; canvas.height = height;
  const ctx = canvas.getContext("2d"); if (!ctx) return;
  const colors = THEMES[options.theme]; const margin = 54; const headerHeight = options.format === "story" ? 245 : 190;
  const gradient = ctx.createLinearGradient(0, 0, width, height); gradient.addColorStop(0, colors.top); gradient.addColorStop(1, colors.bottom); ctx.fillStyle = gradient; ctx.fillRect(0, 0, width, height);
  roundedRect(ctx, margin, margin, width - margin * 2, height - margin * 2, 28); ctx.fillStyle = colors.paper; ctx.fill();
  ctx.save(); roundedRect(ctx, margin, margin, width - margin * 2, headerHeight, 28); ctx.clip(); ctx.fillStyle = colors.top; ctx.fillRect(margin, margin, width - margin * 2, headerHeight); ctx.restore();
  ctx.fillStyle = colors.accent; ctx.font = "800 42px Arial"; ctx.fillText("C7 STORE", margin + 42, margin + 82);
  ctx.font = "700 20px Arial"; ctx.fillText(options.headline.toUpperCase().slice(0, 52), margin + 42, margin + 132);
  const imageTop = margin + headerHeight + 34; const imageHeight = options.format === "story" ? 720 : options.format === "square" ? 430 : 540; const imageX = margin + 42; const imageWidth = width - (margin + 42) * 2;
  roundedRect(ctx, imageX, imageTop, imageWidth, imageHeight, 20); ctx.fillStyle = "#eaf3f7"; ctx.fill();
  if (product.imageUrl) { try { const image = await loadUrl(product.imageUrl); ctx.save(); roundedRect(ctx, imageX, imageTop, imageWidth, imageHeight, 20); ctx.clip(); const scale = options.imageFit === "cover" ? Math.max(imageWidth / image.width, imageHeight / image.height) : Math.min(imageWidth / image.width, imageHeight / image.height); const drawWidth = image.width * scale, drawHeight = image.height * scale; ctx.drawImage(image, imageX + (imageWidth - drawWidth) / 2, imageTop + (imageHeight - drawHeight) / 2, drawWidth, drawHeight); ctx.restore(); } catch { /* placeholder below */ } }
  if (!product.imageUrl) { ctx.fillStyle = colors.accent; ctx.font = "800 120px Arial"; ctx.textAlign = "center"; ctx.fillText("C7", width / 2, imageTop + imageHeight / 2 + 35); ctx.textAlign = "left"; }
  let y = imageTop + imageHeight + 54;
  ctx.fillStyle = colors.accent; ctx.font = "700 22px Arial"; ctx.fillText(`${product.category.toUpperCase()} · ${product.brand.toUpperCase()}`.slice(0, 55), imageX, y); y += 68;
  ctx.fillStyle = colors.text; const titleSize = fitText(ctx, product.model, imageWidth, options.format === "story" ? 64 : 58); ctx.font = `800 ${titleSize}px Arial`; ctx.fillText(product.model.slice(0, 40), imageX, y); y += 54;
  ctx.fillStyle = colors.soft; ctx.font = "24px Arial";
  if (options.showProcessor) { ctx.fillText(product.processor.slice(0, 58), imageX, y); y += 42; }
  if (options.showSpecs) { ctx.fillText([product.ram, product.storage, product.screen].filter(Boolean).join(" · ").slice(0, 70), imageX, y); y += 42; }
  if (options.showCondition) { ctx.fillText((product.cosmeticCondition || product.condition).slice(0, 62), imageX, y); y += 46; }
  if (options.showPrice) { ctx.fillStyle = colors.accent; ctx.font = "800 48px Arial"; ctx.fillText(product.promoPrice || product.price, imageX, y + 22); y += 78; }
  if (options.showContact) { const contactY = Math.min(height - margin - 55, Math.max(y + 15, height - margin - 90)); ctx.fillStyle = colors.text; ctx.font = "700 22px Arial"; ctx.fillText("WhatsApp (51) 3055-3090  ·  @c7tec_store", imageX, contactY); }
}

export default function CardDesigner({ product, onClose }: { product: CardProduct; onClose: () => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [options, setOptions] = useState<Options>({ format: "whatsapp", theme: "classic", headline: "Seminovo revisado", showProcessor: true, showSpecs: true, showCondition: true, showPrice: true, showContact: true, imageFit: "contain" });
  const [rendering, setRendering] = useState(false);
  const dimensions = FORMATS[options.format];
  const update = <K extends keyof Options>(key: K, value: Options[K]) => setOptions((current) => ({ ...current, [key]: value }));
  const renderKey = useMemo(() => JSON.stringify(options), [options]);
  useEffect(() => { if (!canvasRef.current) return; setRendering(true); renderCard(canvasRef.current, product, options).finally(() => setRendering(false)); }, [product, renderKey]);
  async function createBlob() { const canvas = canvasRef.current; if (!canvas) return null; await renderCard(canvas, product, options); return new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/png")); }
  async function download() { const blob = await createBlob(); if (!blob) return; const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = (`c7-${options.format}-${product.brand}-${product.model}.png`).replace(/[^a-z0-9.-]+/gi, "-"); link.click(); URL.revokeObjectURL(link.href); }
  async function share() { const blob = await createBlob(); if (!blob) return; const file = new File([blob], `c7-${product.brand}-${product.model}.png`, { type: "image/png" }); if (navigator.canShare?.({ files: [file] })) await navigator.share({ files: [file], title: `${product.brand} ${product.model} · C7 Store` }); else await download(); }
  return <div className="confirm-modal-backdrop card-designer-backdrop" role="presentation"><div className="card-designer-modal" role="dialog" aria-modal="true" aria-labelledby="card-designer-title"><button className="close-button" onClick={onClose} aria-label="Fechar criador de card"><X size={18} /></button><div className="card-designer-heading"><div><span className="admin-kicker">/ divulgação personalizada</span><h2 id="card-designer-title">Crie o card antes de baixar.</h2><p>Escolha formato, aparência e informações. A prévia atualiza automaticamente.</p></div><span>{dimensions.width} × {dimensions.height}px</span></div><div className="card-designer-layout"><div className="card-preview-stage">{rendering && <div className="card-rendering"><Loader2 className="spin" size={24} /></div>}<canvas ref={canvasRef} /></div><div className="card-options"><fieldset><legend>Formato</legend><div className="card-option-grid format-grid">{(Object.keys(FORMATS) as Format[]).map((format) => <button key={format} className={options.format === format ? "active" : ""} onClick={() => update("format", format)}>{format === "story" ? <Instagram size={15} /> : <ImageDown size={15} />}{FORMATS[format].label}</button>)}</div></fieldset><fieldset><legend>Tema</legend><div className="theme-options">{(["classic", "light", "offer"] as Theme[]).map((theme) => <button key={theme} className={`${theme} ${options.theme === theme ? "active" : ""}`} onClick={() => update("theme", theme)}><span />{theme === "classic" ? "C7 Azul" : theme === "light" ? "Claro" : "Oferta"}</button>)}</div></fieldset><label className="card-headline"><span>Chamada do card</span><input value={options.headline} maxLength={52} onChange={(event) => update("headline", event.target.value)} /></label><fieldset><legend>Informações visíveis</legend><div className="card-checks">{([['showProcessor','Processador'],['showSpecs','RAM, armazenamento e tela'],['showCondition','Estado de conservação'],['showPrice','Preço'],['showContact','Contato C7']] as Array<[keyof Options,string]>).map(([key,label]) => <label key={key}><input type="checkbox" checked={Boolean(options[key])} onChange={(event) => update(key, event.target.checked as never)} /><Check size={13} /> {label}</label>)}</div></fieldset><fieldset><legend>Foto no card</legend><div className="card-option-grid"><button className={options.imageFit === "contain" ? "active" : ""} onClick={() => update("imageFit", "contain")}>Mostrar inteira</button><button className={options.imageFit === "cover" ? "active" : ""} onClick={() => update("imageFit", "cover")}>Preencher área</button></div></fieldset></div></div><div className="card-designer-actions"><button className="admin-secondary" onClick={onClose}>Cancelar</button><button className="admin-secondary" onClick={() => void share()}><Share2 size={15} /> Compartilhar</button><button className="admin-primary" onClick={() => void download()}><Download size={15} /> Baixar PNG</button></div></div></div>;
}
